// Builds COPY.md — a readable snapshot of every word of site copy — from the
// JSON under content/. Shared by scripts/export-copy.mjs (CLI) and the Studio
// publish route, so both produce byte-identical output.
//
// Plain .mjs so the CLI can run it with bare node and the TS route can import it.

// Keys that hold assets, layout, or routing — not copy.
const SKIP_KEYS = new Set([
  'photoSrc', 'photoSrcMobile', 'src', 'image', 'imageSrc', 'logoSrc', 'icon',
  'href', 'url', 'link', 'slug', 'id', 'align', 'baseRot', 'wrapperHeight',
  'width', 'height', 'order', 'variant', 'color', 'className', 'showOn',
  'alt', 'video', 'videoSrc', 'poster', 'anchor',
])

const PAGE_ORDER = ['home', 'about', 'work-with-me', 'speaking']

const isCopy = (v) =>
  typeof v === 'string' && v.trim() !== '' && !/^[/#]|^https?:\/\//.test(v.trim())

const titleize = (k) =>
  k.replace(/([A-Z])/g, ' $1').replace(/[-_]/g, ' ').replace(/^./, (c) => c.toUpperCase()).trim()

// Walk any shape and emit markdown. Objects become headings, arrays of objects
// become numbered items, strings become the copy itself.
function walk(node, depth, label, out) {
  if (Array.isArray(node)) {
    node.forEach((item, i) => {
      if (isCopy(item)) out.push(item, '')
      else if (item && typeof item === 'object') {
        out.push(`${'#'.repeat(Math.min(depth, 6))} ${label} ${i + 1}`, '')
        walk(item, depth + 1, label, out)
      }
    })
    return
  }

  if (node && typeof node === 'object') {
    for (const [key, value] of Object.entries(node)) {
      if (SKIP_KEYS.has(key)) continue
      if (isCopy(value)) {
        out.push(`**${titleize(key)}** — ${value}`, '')
      } else if (Array.isArray(value) && value.length && value.every(isCopy)) {
        out.push(`**${titleize(key)}**`, '')
        value.forEach((v) => out.push(v, ''))
      } else if (value && typeof value === 'object') {
        out.push(`${'#'.repeat(Math.min(depth, 6))} ${titleize(key)}`, '')
        walk(value, depth + 1, titleize(key), out)
      }
    }
  }
}

function section(name, raw, out) {
  let data
  try {
    data = JSON.parse(raw)
  } catch {
    return // a malformed file should never block a publish
  }
  if (Array.isArray(data) ? data.length === 0 : Object.keys(data || {}).length === 0) return
  out.push(`## ${titleize(name)}`, '')
  walk(data, 3, titleize(name), out)
}

const baseName = (p) => p.split('/').pop().replace(/\.json$/, '')

/**
 * @param {Record<string, string>} files  content/**\/*.json path -> raw JSON string
 * @param {string} [today]  ISO date (YYYY-MM-DD); defaults to now
 * @returns {string} markdown
 */
export function buildCopyMarkdown(files, today) {
  const date = today || new Date().toISOString().slice(0, 10)

  const pages = Object.keys(files)
    .filter((p) => p.startsWith('content/pages/') && p.endsWith('.json'))
    .sort((a, b) => {
      const ia = PAGE_ORDER.indexOf(baseName(a))
      const ib = PAGE_ORDER.indexOf(baseName(b))
      return (ia < 0 ? 99 : ia) - (ib < 0 ? 99 : ib) || a.localeCompare(b)
    })

  const collections = Object.keys(files)
    .filter((p) => p.startsWith('content/collections/') && p.endsWith('.json'))
    .sort()

  const out = [
    '# Site Copy',
    '',
    '_Generated from `content/` on every Studio publish. Do not edit this file — edit the page JSON or use Studio._',
    '',
    `_Last generated: ${date}_`,
    '',
    '---',
    '',
  ]

  if (pages.length) {
    out.push('# Pages', '')
    pages.forEach((p) => section(baseName(p), files[p], out))
  }

  if (collections.length) {
    out.push('---', '', '# Collections', '')
    collections.forEach((p) => section(baseName(p), files[p], out))
  }

  return out.join('\n').replace(/\n{3,}/g, '\n\n')
}
